In [2]:
import numpy as np
import math

### Basic Arithmetic

In [3]:
scalar_a = 15
scalar_b = 4

In [10]:
print("\n --- Basic Arithmetic Operation---")
print(f"Adddition: {scalar_a} + {scalar_b} = {scalar_a + scalar_b}")
print(f"Integer Divison:{scalar_a}//{scalar_b} = {scalar_a//scalar_b}")
print(f"Exponentiation:{scalar_a}^{scalar_b} ={scalar_a**scalar_b}")


 --- Basic Arithmetic Operation---
Adddition: 15 + 4 = 19
Integer Divison:15//4 = 3
Exponentiation:15^4 =50625


### Complex Numbers

In [11]:

c1 = 2 + 3j
c2 = 1 -1j
print("\n---Complex Number Operations----")
print(f"Complex numbers addition:{c1} + {c2} = {c1} +{c2}")
print(f"Magnitude of {c1}:{abs(c1):.2f}")


---Complex Number Operations----
Complex numbers addition:(2+3j) + (1-1j) = (2+3j) +(1-1j)
Magnitude of (2+3j):3.61


### Floating Point Precision

In [14]:
val_one = 0.1 + 0.2
val_two = 0.3

print("\n Floating Point Precision")
print(f"Is 0.1 + 0.2 equal to 0.3? {val_one == val_two}")
print(f"Actual value of 0.1 + 0.2:{val_two}")

# use math.isclose() for float comparison

print(f"Are {val_one} and {val_two} close enough? {math.isclose(val_one,val_two)}")


 Floating Point Precision
Is 0.1 + 0.2 equal to 0.3? False
Actual value of 0.1 + 0.2:0.3
Are 0.30000000000000004 and 0.3 close enough? True


### Sets 
#### Sets are collection of unique elements.


In [ ]:
# set creattion, Union and Intersection

set_A = {1,2,3,4}
set_B = {3,4,5,6}

print("\n -----Set creation, union and intersection of sets----")
print(f"Set A :{set_A} | Set B :{set_B}")

# union of Sets A and B, all unique elements,set does not allow duplicates
print(f"Union (A U B):{set_A.union(set_B)}")

# intersection of Sets A and B
print(f"Intersection (A n B) {set_A.intersection(set_B)}")



 -----Set creation, union and intersection of sets----
Set A :{1, 2, 3, 4} | Set B :{3, 4, 5, 6}
Union (A U B):{1, 2, 3, 4, 5, 6}
Intersection (A n B) {3, 4}


### Set Differences


In [ ]:
print("\n ----- Set diffferences-----")
print(f"Difference (A\\B)[elements in set A and not in Set B]:{set_A.difference(set_B)}")

# A symmetric set difference
print(f"Symmetric Difference (elements in A or B ,but not both):{set_A.symmetric_difference(set_B)}")


 ----- Set diffferences-----
Difference (A\B)[elements in set A and not in Set B]:{1, 2}
Symmetric Difference (elements in A or B ,but not both):{1, 2, 5, 6}


#### Subsets and Supersets

In [24]:
set_C = {1,2}
print("\n ----Subsets and supersets-----")
print(f"Set C:{set_C}")
print(f"Is C a subset of A? {set_C.issubset(set_A)}")
print(f"Is set A a superset of C? {set_A.issuperset(set_C)}")


 ----Subsets and supersets-----
Set C:{1, 2}
Is C a subset of A? True
Is set A a superset of C? True


### Vector Creattion and Vector Addition

In [26]:
v = np.array([2,4,6])
u = np.array([1,-1,3])
print("\n --- Creation and Addition----")
print(f"Vector v: {v}")
print(f"Vector u : {u}")
print(f"Addition of vectors u and v:{u + v}")


 --- Creation and Addition----
Vector v: [2 4 6]
Vector u : [ 1 -1  3]
Addition of vectors u and v:[3 3 9]


### Scalar multiplication and Norm (Length)
#### scaling a vector changes its length. The norm is its actual length


In [27]:
scalar = 3
scaled_v = scalar * v
norm_v = np.linalg.norm(v)

print("\n ---- Scalar Multiplication and Norm ----")

print(f"Scalar Multiplication (3 * v):{scaled_v}")
print(f"The Norm of {v}:{norm_v}")


 ---- Scalar Multiplication and Norm ----
Scalar Multiplication (3 * v):[ 6 12 18]
The Norm of [2 4 6]:7.483314773547883


### The Dot Product and Orthogonality

#### Dot product measures how much vectors point in the same direction.
#### If the dot product is 0 ,vectors are orthogonal

In [29]:
v1 = np.array([1,0,0]) 
v2 = np.array([0,1,0])

dot_product = np.dot(v1,v2)
print("\n ---- Dot product and Orthogonality----")
print(f"Vector v1:{v1},Vector v2:{v2}")
print(f"Dot product (v1 . v2):{dot_product}")

if dot_product == 0:
    print(f"Vectors {v1} and {v2} are orthogonal.")
else:
    print(f"vectors {v1} and {v2} are not orthogonal.")


 ---- Dot product and Orthogonality----
Vector v1:[1 0 0],Vector v2:[0 1 0]
Dot product (v1 . v2):0
Vectors [1 0 0] and [0 1 0] are orthogonal.


### Matrices (2D arrays with numpy)


In [31]:
A = np.array([
    [10,10,10],
    [20,20,20]
])

print("\n --- Creation, Shape and Transpose of a matrix")
print(f"Matrix A:\n",A)
print(f"The shape of matrix A:{A.shape} (rows,columns)")

# Transpose flit rows into columns
print(f" Transpose of A:\n",A.T)



 --- Creation, Shape and Transpose of a matrix
Matrix A:
 [[10 10 10]
 [20 20 20]]
The shape of matrix A:(2, 3) (rows,columns)
 Transpose of A:
 [[10 20]
 [10 20]
 [10 20]]


#### Matrix Addition and Scalar Multiplication

In [32]:
B = np.array([
    [10,10,10],
    [20,20,20]
])

print("\n Matrix Addition and Scalar Multiplication")
print(f"Matrix B:\n",B)
print(f"A + B:\n",A + B)
print(f"2 * A:\n",2*A)


 Matrix Addition and Scalar Multiplication
Matrix B:
 [[10 10 10]
 [20 20 20]]
A + B:
 [[20 20 20]
 [40 40 40]]
2 * A:
 [[20 20 20]
 [40 40 40]]


### Matrix Multiplication
#### To multiply (m x n) by (n x p) inner dimensions (n) must match.
#### use @ or np.dot()

In [34]:
C = np.array(
    [
        [1,2],
        [3,4,],
        [5,6]
    ]
)

# 3 x 2 matrix
print("\n --- matrix multiplication---")
print(f"Multiply A (2 x 3) with C (3 x 2) results in a 2 X 2 matrix")

matrix_product = A @ C
print(matrix_product)



 --- matrix multiplication---
Multiply A (2 x 3) with C (3 x 2) results in a 2 X 2 matrix
[[ 90 120]
 [180 240]]


### The Identity matrix

In [35]:
I = np.eye(3)
print("\n---- The Identity Matrix ----")
print("3 x 3 Identity matrix(I):\n",I)


---- The Identity Matrix ----
3 x 3 Identity matrix(I):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Zeros and Ones matrices
#### Useful for initializing arrays before filling them with calculated data

In [36]:
Z = np.zeros((2,3))
O = np.ones((3,1))

print(" 2 x 3 matrix :\n",Z)
print("3 x 1 matrix:\n",O)

 2 x 3 matrix :
 [[0. 0. 0.]
 [0. 0. 0.]]
3 x 1 matrix:
 [[1.]
 [1.]
 [1.]]


### Diagonal Matrices

In [38]:
D = np.diag([5,10,15])

print("Diagonal Matrix from list [5,10,15]:\n",D)

Diagonal Matrix from list [5,10,15]:
 [[ 5  0  0]
 [ 0 10  0]
 [ 0  0 15]]


#### Determinants
##### The determinanr tells us the scaling factor of the linear transformation.

##### If det = 0 , the matrix collapses space and is not invertible.


In [39]:
M = np.array(
    [
        [3,8],
        [4,6]
    ]
)

det_M = np.linalg.det(M)
print("Sqaure matrix M:\n",M)
print(f"The determinant of M:{det_M:.2f}")

Sqaure matrix M:
 [[3 8]
 [4 6]]
The determinant of M:-14.00
